# Generated by Django 5.2.16 on 2026-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
